config/routes.rb
Rails.application.routes.draw do
  get 'paginas/inicio', as: 'inicio'
  get 'paginas/consulta', as: 'consulta'
  get 'paginas/estadistica', as: 'estadistica'


  devise_for :users, path: '', path_names: { sign_in: 'ingresar', sign_out: 'Salir', sign_up: 'registrar'}

  resources :expedientes do
    delete :delete_upload_documentos
  end
  
  resources :estatus_procesals
  resources :estatus_audiencias
  resources :entidad_responsables
  resources :audiencias
  resources :audit_logs
  resources :holidays
  resources :abogados
  resources :links
  resources :accion_instancia
  resources :cuestionarios
  resources :despachos
  
  
  root to: "paginas#inicio" 


end

app/models/abogado.rb
class Abogado < ApplicationRecord
  validates_presence_of :nombre, :iniciales
 
  
  before_save :to_upper

  def to_upper
    attributes.keys.each do |attribute|
      self[attribute].try(:upcase!)
    end
  end
end

app/models/accion_instancium.rb
class AccionInstancium < ApplicationRecord
    validates_presence_of  :accion

    before_save :to_upper

  def to_upper
    attributes.keys.each do |attribute|
      self[attribute].try(:upcase!)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audiencium.rb
class Audiencium < ApplicationRecord
  belongs_to :expediente

  before_save :to_upper


  private
  def to_upper
    attributes.keys.each do |attribute|
      self[attribute].try(:upcase!)
    end
  end
  
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
	include PgSearch::Model

	belongs_to :user

	  pg_search_scope :search_by_full_auditlog, against: [:expediente, :entidad_responsable, :socio, 
	  	:estado_procesal, :ubicacion_fisica, :despacho, :referencia1, :referencia2, :referencia3, :comentarios, :archivo, :anio, 
	  	:fecha_audiencia, :asignado_audiencia, :comentarios_audicencia, :estatus, :accion], 
                        using:   {tsearch: { prefix: true }}

	def self.nombre_usuario(user_id)
		nombre = User.find(id: user_id)
	end	
	
	def audiencias(cadena)
		 return cadena.split(",")
	end

	def expediente_id(expediente)
		expediente_id = Expediente.where(expediente: expediente)
		
	end
end



 

app/models/cuestionario.rb
class Cuestionario < ApplicationRecord
    include PgSearch::Model
    
    has_many_attached :cuestionarios

    before_save :to_upper

    validates_presence_of :nombre, :appaterno, :apmaterno

    pg_search_scope :search_by_full_cuestionario, against: [:nombre, :appaterno, :apmaterno, :empresa], 
                    using:   {tsearch: { prefix: true }}
     

    def to_upper
  	  attributes.keys.each do |attribute|
  	    [attribute].try(:upcase!)
  	  end
    end

end

 
 

app/models/denuncia_penal.rb
class DenunciaPenal < ApplicationRecord

 
end

app/models/despacho.rb
class Despacho < ApplicationRecord
	has_many :locations, inverse_of: :despacho, dependent: :destroy 
	 

	accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

	def abogado(id)
    	abogado = Abogado.where(id: id).first.nombre
    end 

end

app/models/estatus_audiencia.rb
class EstatusAudiencia < ApplicationRecord
 
end

app/models/estatus_procesal.rb
class EstatusProcesal < ApplicationRecord

	validates_uniqueness_of :estatus
	validates_presence_of :estatus

	 
	 
end

app/models/expediente.rb
class Expediente < ApplicationRecord
	include PgSearch::Model

	before_save :to_upper
	belongs_to :user
	belongs_to :entidad_responsable
	belongs_to :estatus_procesal
	

	has_many_attached :documentos
	
	has_many :audiencia_expedientes, inverse_of: :expediente, dependent: :destroy 
	has_many :resumen_expedientes, inverse_of: :expediente, dependent: :destroy  
	has_many :resumen_links, inverse_of: :expediente, dependent: :destroy  
	 
	

	enum cliente: {demandante: 0, demandado: 1}
	
	validates_uniqueness_of :expediente
	validates_presence_of :anio, :expediente, :demandante, :demandado, :socio, :location, :entidad_responsable_id 
	
	accepts_nested_attributes_for :audiencia_expedientes, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :resumen_expedientes, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :resumen_links, reject_if: :all_blank, allow_destroy: true
	 
	validates :resumen_expedientes, :presence => true
	
	pg_search_scope :search_by_full_expediente, against: [:expediente, :demandante, :demandado, :entidad_responsable, 
														  :socio, :ubicacion_fisica, :despacho, 
														  :referencia1, :referencia2, :referencia3, :anio], 
												using:   {tsearch: { prefix: true }}

	
	scope :expediente_por_anio, -> (anio) {where("anio= ?", anio)}

	scope :expediente_por_entidad, ->(entidad)	{ where("entidad_responsable= ?", entidad.to_s)}

	def nombre_socio
		nombre_socio = Abogado.where(id: socio).first.nombre
	  end
	  
	def colonia(location)
    	despacho = Location.where(alias: location).first.despacho.colonia
    end  
  	 

  	def to_upper
  	  attributes.keys.each do |attribute|
  	    [attribute].try(:upcase!)
  	  end
  	end

  	def self.proximas_audiencias
  		inicio_semana = Date.today 
		fin_semana = inicio_semana + 7.days
		prox_audiencias = Expediente.find_by_sql("select t1.entidad_responsable_id, count(t1.entidad_responsable_id) 
												   from expedientes t1, audiencia_expedientes t2 
												   where  t2.expediente_id = t1.id and t2.fecha >= '#{inicio_semana}' 
												   and t2.fecha <= '#{fin_semana}' GROUP BY t1.entidad_responsable_id" )
 
	  end
	    
end

app/models/holiday.rb
class Holiday < ApplicationRecord
	before_validation :rellena_campos

	def rellena_campos
		self.comentarios = self.expediente_id
		self.asignado = self.expediente_id
		self.estatus = 'vacaciones'
		 
	end
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :despacho

     

     
     
end

app/models/resumen_expediente.rb
class ResumenExpediente < ApplicationRecord
  belongs_to :expediente
  belongs_to :estatus_procesal

  has_one_attached :escrito
end

app/models/resumen_link.rb
class ResumenLink < ApplicationRecord
  belongs_to :expediente
  belongs_to :accion_instancium
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :abogado], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, :trackable 

  #find_for_database_authentication

  validates :socio, presence: :true, uniqueness: { case_sensitive: false }

  has_many :expedientes
  has_many :audit_logs

end

app/helpers/abogados_helper.rb
module AbogadosHelper
end

app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/compartidos/_footer.html.erb
<footer id="footer">
  <p><%= @copyright %> </p>
  <p>created by @swat </p>
</footer>

app/views/compartidos/_navegacion.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-menu">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
    </div>
    
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li>
          <% if current_user %>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.socio.upcase %> <span></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "salir", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to "perfil", edit_user_registration_path %></li>
            </ul>
          <% else %>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Ingresar<span></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "ingresar", new_user_session_path %></li>
            </ul>
          <% end %>
        </li>
        <% if current_user %>
          <li><%= link_to "Inicio", root_path %></li>
          <li><%= link_to "Expedientes", expedientes_path %></li>
          <% if current_user.has_role?(:admin) %>
            <li><%= link_to "Audiencias", audiencias_path %></li>
            <li><%= link_to "Bitácora", audit_logs_path %></li>
            <li>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Catálogos<span></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Estado Procesal Expediente", estatus_procesals_path %></li>
              <li><%= link_to "Estado Audiencia", estatus_audiencias_path %></li>
              <li><%= link_to "Entidad Responsable", entidad_responsables_path %></li>
              <li><%= link_to "Vacaciones y Festivos", holidays_path %></li>
              <li><%= link_to "Abogados litigantes", abogados_path %></li>
              <li><%= link_to "Links externos", links_path %></li>
              <li><%= link_to "Acción instancia", accion_instancia_path %></li>
              <li><%= link_to "Ubicación Física", despachos_path %></li>
            </ul>
          </li>
          <li><%= link_to "Cuestionarios", cuestionarios_path %></li>
          <li><%= link_to "Resumen", consulta_path %></li>
           
          <% end %>
      </ul>
        <div class="nav navbar-right navbar-btn">
          <%= link_to  new_expediente_path, class: "btn btn-primary" do %>
            <i class="glyphicon glyphicon-plus"></i> 
            Nuevo Expediente
          <% end %>
        </div>
        <% end %>
       
 
  </div>
</nav>

app/views/compartidos/_sidebar.html.erb
 <% @prox_audiencias = Expediente.proximas_audiencias  %>
 <% @links = Link.all %>
 
<div class="list-group">
    <% active = params[:entidad_responsable_id] == nil || params[:entidad_responsable_id].empty? ? 'active' : '' %>
     
  	<%= link_to expedientes_path, class: "list-group-item #{active}" do %>
  		EXPEDIENTES <span class="badge"><%= Expediente.all.count %></span>
  	<% end %>
  	
    <% tot_prox_audiencias = 0 %>
  	<% @prox_audiencias.each do |a| %>
  		<% tot_prox_audiencias = tot_prox_audiencias + a.count %>
  	<% end %>

  	<%= link_to root_path, class: "list-group-item #{active}" do %>
  		PRÓXIMAS AUDIENCIAS <span class="badge"><%= tot_prox_audiencias %></span>
  	<% end %>	
  	
    
  	<% @prox_audiencias.each do |a| %>
      <% active = params[:entidad_responsable_id].to_i == a.entidad_responsable_id ?  'active' : '' %>
      <%= link_to inicio_path(entidad_responsable_id: a.entidad_responsable_id), class: "list-group-item #{active}"  do %>
		    <%= a.entidad_responsable.nombre.upcase  %><span class="badge"><%= a.count %></span>
      <% end %>
	 <% end %>

<br>

 <div class="links">
  <span class="list-group-item active">LINKS EXTERNOS </span>
  <% @links.each do |link| %>
    <%= link_to link.link , class: "list-group-item", onclick: "return check('#{link.link}');", target: "_blank" do %>
      <%= link.entidad.humanize %><span class="badge"><i class="glyphicon glyphicon-link"></i></span>
    <% end %>
  <% end %>
  </div>
</div>
 

  <script>
    var check = function(valor ) {
    console.log(valor);
    $.ajax({
      type: "POST",
      url: "/audit_logs/",
      data: {
        archivo: valor,
        accion: 'Consulta link Externo',      
      },
      error: function(error) {
            console.log(error);
            return false;
          },
  success: function(data) {
             console.log(data);
             return false;
          },

    })


}
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expedientes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'compartidos/navegacion' %>

    <% flash.each do |key, message| %>
      <div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
        <%= message %> 
      </div>
    <% end %>

    <%= yield %>
  
  </body>
  
  <%= render 'compartidos/footer' %>

</html>


   