config/routes.rb
Rails.application.routes.draw do
  get 'paginas/inicio', as: 'inicio'
  get 'paginas/consulta', as: 'consulta'
  get 'paginas/estadistica', as: 'estadistica'


  devise_for :users, path: '', path_names: { sign_in: 'ingresar', sign_out: 'Salir', sign_up: 'registrar'}

  resources :expedientes do
    delete :delete_upload_documentos
  end
  
  resources :estatus_procesals
  resources :estatus_audiencias
  resources :entidad_responsables
  resources :audiencias
  resources :audit_logs
  resources :holidays
  resources :abogados
  resources :links
  resources :accion_instancia
  resources :cuestionarios
  resources :despachos
  
  
  root to: "paginas#inicio" 


end

app/models/holiday.rb
class Holiday < ApplicationRecord
	before_validation :rellena_campos

	def rellena_campos
		self.comentarios = self.expediente_id
		self.asignado = self.expediente_id
		self.estatus = 'vacaciones'
		 
	end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
	before_action :set_holiday, only: [:edit, :update, :destroy]
	access admin: :all

	def index
		@holidays = Holiday.order('fecha')
    AuditLog.create!(current_sign_in_ip: current_user.current_sign_in_ip,  user_id: current_user.id, accion: 'Menú Holidays' )
	end

	def new
		@holiday = Holiday.new
	end

	def edit

	end

	def create
    	@holiday = Holiday.new(holiday_params)

    	respond_to do |format|

      		if @holiday.save
        		format.html { redirect_to holidays_path, notice: 'Regsitro creado correctamente.' }
      		else
        		format.html { render :new }
      		end
    	end
  	end

  	def update
  	  respond_to do |format|
  	    if @holiday.update(holiday_params)
  	      format.html { redirect_to  holidays_path, notice: 'Regsitro actualizado correctamente.' }
  	    else
  	      format.html { render :edit }
  	    end
  	  end
  	end

  	def destroy
  	  @holiday.destroy
  	  respond_to do |format|
  	    format.html { redirect_to holidays_path, notice: 'Regsitro eliminado correctamente.' }
  	  end
  	end

  	private
    
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    def holiday_params
      params.require(:holiday).permit(:id, :fecha, :asignado, :comentarios, :expediente_id)
    end

end

 

app/views/holidays/_form.html.erb
<%= form_for(@holiday, html: { multipart: true }, remote: local_assigns[:hide_buttons]) do |form| %>
<% if @holiday.errors.any? %>
      <% @holiday.errors.full_messages.each do |message| %>
         <%= js add_gritter(message, title: "Aviso", sticky: false) %>
      <% end %>
  <% end %>

<div class="field">
  <%= form.label :comentarios %>
  <%= form.text_field :expediente_id, class: "form-control", placeholder: "Descripción" %>
</div>
<div class="field">
  <%= form.label :fecha %>
  <%= form.date_field :fecha, class: "form-control", placeholder: "Fecha" %>
</div>

  <br>
  <% unless local_assigns[:hide_buttons] %>
  <div class="actions">&nbsp;
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
      <span><i class="glyphicon glyphicon-pencil"></i> Guardar</span>
    <% end %>  
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
      <span><i class="glyphicon glyphicon-list"></i></span>
      Catálogo
    </button>
  </div>
  <% end %>
<% end %> 

app/views/holidays/edit.html.erb
<%= form_with(model: @holiday, local: true) do |form| %>
  <%= form.date_field :fecha, placeholder: 'Fecha aaaa-mm-dd' %>
  <%= form.text_area :expediente_id, cols:50, rows: 2, placeholder: 'Descripción' %>
  <%= form.submit "Guardar", class: 'btn btn-success' %>
<% end %>
<%= link_to "Regresar a Catálogo", holidays_path, class: "btn btn-primary" %>

app/views/holidays/edit.js.erb
$('#form-modal-title').html("<i class='glyphicon glyphicon-plus'></i>&nbsp;&nbsp;Modificar Fecha");
$('#form-modal-body').html('<%= j render("form" ) %>');
$('#form-modal').modal('show');
$('#form-modal-save-btn').click(function() {
	$('#new_tipo_montaje').submit();
});

app/views/holidays/index.html.erb
<div class="container">
	<h4>Catálogo de dias Festivos y Vacaciones</h4>
	<%= link_to "Agregar Fecha", new_holiday_path, class: "btn btn-primary" %>
	<%= link_to "Regresar a Expedientes", expedientes_path, class: "btn btn-info" %>
	<table class="table">
		<thead>
			<tr>
				<th>id</th>
				<th>Fecha</th>
				<th>Descripción</th>
			</tr>
		</thead>
		<tbody>
			<% @holidays.each do |holiday| %>
				<tr>
					<td><%= holiday.id %></td>
					<td><%= holiday.fecha %></td>
					<td><%= holiday.expediente_id %></td>
					<td><%= link_to 'Editar', edit_holiday_path(holiday) %></td>
					<td><%= link_to 'Eliminar', holiday, method: :delete, data: { confirm: '¿Confirma eliminar el Registro?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

 

app/views/holidays/new.html.erb
<%= form_with(model: @holiday, local: true) do |form| %>
  <%= form.date_field :fecha, placeholder: 'Fecha aaaa-mm-dd' %>
  <%= form.text_area :expediente_id, cols:50, rows: 2, placeholder: 'Descripción' %>
  <%= form.submit "Guardar", class: 'btn btn-success' %>
<% end %>
<%= link_to "Regresar a Catálogo", holidays_path, class: "btn btn-primary" %>
 

app/views/holidays/new.js.erb
$('#form-modal-title').html("<i class='glyphicon glyphicon-plus'></i>&nbsp;&nbsp;Ingresar Fecha");
$('#form-modal-body').html('<%= j render("form" ) %>');
$('#form-modal').modal('show');
$('#form-modal-save-btn').click(function() {
	$('#new_tipo_montaje').submit();
});