config/routes.rb
Rails.application.routes.draw do
  get 'paginas/inicio', as: 'inicio'
  get 'paginas/consulta', as: 'consulta'
  get 'paginas/estadistica', as: 'estadistica'


  devise_for :users, path: '', path_names: { sign_in: 'ingresar', sign_out: 'Salir', sign_up: 'registrar'}

  resources :expedientes do
    delete :delete_upload_documentos
  end
  
  resources :estatus_procesals
  resources :estatus_audiencias
  resources :entidad_responsables
  resources :audiencias
  resources :audit_logs
  resources :holidays
  resources :abogados
  resources :links
  resources :accion_instancia
  resources :cuestionarios
  resources :despachos
  
  
  root to: "paginas#inicio" 


end

app/models/expediente.rb
class Expediente < ApplicationRecord
	include PgSearch::Model

	before_save :to_upper
	belongs_to :user
	belongs_to :entidad_responsable
	belongs_to :estatus_procesal
	

	has_many_attached :documentos
	
	has_many :audiencia_expedientes, inverse_of: :expediente, dependent: :destroy 
	has_many :resumen_expedientes, inverse_of: :expediente, dependent: :destroy  
	has_many :resumen_links, inverse_of: :expediente, dependent: :destroy  
	 
	

	enum cliente: {demandante: 0, demandado: 1}
	
	validates_uniqueness_of :expediente
	validates_presence_of :anio, :expediente, :demandante, :demandado, :socio, :location, :entidad_responsable_id 
	
	accepts_nested_attributes_for :audiencia_expedientes, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :resumen_expedientes, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :resumen_links, reject_if: :all_blank, allow_destroy: true
	 
	validates :resumen_expedientes, :presence => true
	
	pg_search_scope :search_by_full_expediente, against: [:expediente, :demandante, :demandado, :entidad_responsable, 
														  :socio, :ubicacion_fisica, :despacho, 
														  :referencia1, :referencia2, :referencia3, :anio], 
												using:   {tsearch: { prefix: true }}

	
	scope :expediente_por_anio, -> (anio) {where("anio= ?", anio)}

	scope :expediente_por_entidad, ->(entidad)	{ where("entidad_responsable= ?", entidad.to_s)}

	def nombre_socio
		nombre_socio = Abogado.where(id: socio).first.nombre
	  end
	  
	def colonia(location)
    	despacho = Location.where(alias: location).first.despacho.colonia
    end  
  	 

  	def to_upper
  	  attributes.keys.each do |attribute|
  	    [attribute].try(:upcase!)
  	  end
  	end

  	def self.proximas_audiencias
  		inicio_semana = Date.today 
		fin_semana = inicio_semana + 7.days
		prox_audiencias = Expediente.find_by_sql("select t1.entidad_responsable_id, count(t1.entidad_responsable_id) 
												   from expedientes t1, audiencia_expedientes t2 
												   where  t2.expediente_id = t1.id and t2.fecha >= '#{inicio_semana}' 
												   and t2.fecha <= '#{fin_semana}' GROUP BY t1.entidad_responsable_id" )
 
	  end
	    
end

app/controllers/expedientes_controller.rb
class ExpedientesController < ApplicationController
	before_action :set_expediente, only: [:show, :edit, :update, :destroy]
  access abogado: {except: [:destroy]}, admin: :all

  def index
    
    if params[:term].present?
      @expedientes = Expediente.search_by_full_expediente(params[:term]).page(params[:page])
    elsif 
      @expedientes = Expediente.all.order(updated_at: 'DESC', expediente: 'DESC').page(params[:page]) 
    end 
    AuditLog.create!(current_sign_in_ip: current_user.current_sign_in_ip,  user_id: current_user.id, accion: 'Menú Expedientes', archivo: params[:term] )

  end

  def show
    AuditLog.create!(expediente: @expediente.expediente, demandante: @expediente.demandante, demandado: @expediente.demandado, 
      entidad_responsable: @expediente.entidad_responsable_id, socio: @expediente.socio, anio: @expediente.anio,  
      email: current_user.email, current_sign_in_ip: current_user.current_sign_in_ip,  user_id: current_user.id, accion: 'Consulta de Expediente' )
  end

  def new
    @expediente = Expediente.new

  end

  def edit
  end

  def create
    @expediente = current_user.expedientes.new(expediente_params)

    respond_to do |format|
      if @expediente.save
        #Crear Registro en la bitácora
        AuditLog.create!(expediente: @expediente.expediente, demandante: @expediente.demandante, demandado: @expediente.demandado, 
          entidad_responsable: @expediente.entidad_responsable_id, socio: @expediente.socio, anio: @expediente.anio,  
          email: current_user.email, current_sign_in_ip: current_user.current_sign_in_ip,  user_id: current_user.id, archivo: expediente_params, accion: 'Creación de Expediente' )
         
        format.html { redirect_to @expediente, notice: 'Registro creado correctamente.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @expediente.update(expediente_params)
        AuditLog.create!(expediente: @expediente.expediente, demandante: @expediente.demandante, demandado: @expediente.demandado, 
          entidad_responsable: @expediente.entidad_responsable_id, socio: @expediente.socio, anio: @expediente.anio,  
          email: current_user.email, current_sign_in_ip: current_user.current_sign_in_ip,  user_id: current_user.id, archivo: expediente_params, accion: 'Actualización de Expediente' )
        format.html { redirect_to @expediente, notice: 'Registro actualizado correctamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    AuditLog.create!(expediente: @expediente.expediente, demandante: @expediente.demandante, demandado: @expediente.demandado, 
  entidad_responsable: @expediente.entidad_responsable_id, socio: @expediente.socio, anio: @expediente.anio,  
  email: current_user.email, current_sign_in_ip: current_user.current_sign_in_ip,  user_id: current_user.id, accion: 'Eliminación de Expediente' )
    @expediente.destroy
    respond_to do |format|
      format.html { redirect_to expedientes_url, notice: 'Registro eliminado correctamente.' }
    end
  end

  def delete_upload_documentos
    @expediente=Expediente.find(params[:expediente_id])
    @expediente.documentos.find_by_id(params[:documentos_id]).purge
    redirect_back(fallback_location: request.referer)
  end


  def linea_tiempo 
      arr = []
      i = 0
      @expediente.audiencia_expedientes.each do |audiencia|
        arr[i] = [i, audiencia.fecha, audiencia.estatus_audiencia.estatus, 'audiencia']
        i = i + 1
      end
      
      @expediente.resumen_expedientes.each do |despacho| 
        arr[i] = [i, despacho.fecha_notificacion, despacho.estatus_procesal.estatus, 'despacho']  
        i = i + 1 
      end 

      @expediente.resumen_links.each do |instancia| 
        arr[i] = [i, instancia.fecha_publicacion, instancia.accion_instancium.accion, 'instancia']  
      i = i + 1 
      end 

      linea_tiempo = arr
    end

  private
    def set_expediente
      @expediente = Expediente.find(params[:id])
    end

    

    def expediente_params
      params.require(:expediente).permit(:anio, :expediente, :demandante, :demandado, :entidad_responsable, :socio, 
                                         :estado_procesal, :estatus_procesal_id, :entidad_responsable_id, :ubicacion_fisica, :despacho, :referencia1, :referencia2, 
                                         :referencia3, :comentarios, :recomendado, :en_sociedad, :archivo, :user_id, :cliente, :location, documentos: [],
                         audiencia_expedientes_attributes: [:id, :fecha, :asignado, :comentarios, :expedientes_id, :estatus, :estatus_audiencia_id, :fecha_fin, 
                                                            :citatorio, :_destroy], 
                         resumen_expedientes_attributes: [:id, :comentarios, :fecha_notificacion, :expediente_id, :estatus_procesal_id, :escrito, :_destroy ],
                         resumen_links_attributes: [:id, :fecha_publicacion, :comentarios, :expediente_id, :accion_instancium_id, :_destroy ]) 
    end

end

 
 

app/helpers/expedientes_helper.rb
module ExpedientesHelper
	def color_año anio, expediente
		case anio
		when 2003
			content_tag(:td, content_tag(:a_href, expediente), class: 'content-box-black')
		when 2006
			content_tag(:td, expediente, class: 'content-box-yellow')
		when 2010
			content_tag(:td, expediente, class: 'content-box-green')
		when 2011
			content_tag(:td, expediente, class: 'content-box-black')
		when 2012
			content_tag(:td, expediente, class: 'content-box-black')
		when 2013
			content_tag(:td, expediente, class: 'content-box-purple')
		when 2014
			content_tag(:td, expediente, class: 'content-box-grey')
		when 2015
			content_tag(:td, expediente, class: 'content-box-rojo')
		when 2016
			content_tag(:td, expediente, class: 'content-box-green')
		when 2017
			content_tag(:td, expediente, class: 'content-box-orange')
		when 2018
			content_tag(:td, expediente, class: 'content-box-blue')
		when 2019
			 content_tag(:td, expediente, class: "content-box-pink")
		when 2020
			content_tag(:td, expediente, class: 'content-box-brown')

		end

	end

	def color_entidad entidad_responsable
		case entidad_responsable
		when  'Junta Federal',  'JUNTA FEDERAL'
			content_tag(:td, entidad_responsable, class: "content-box-federal")
		when  'Junta Local', 'JUNTA LOCAL'  
			content_tag(:td, entidad_responsable, class: "content-box-local")
		when  'Burocrático', 'BUROCRÁTICO' 
			content_tag(:td, entidad_responsable, class: "content-box-buro") 
		else
			content_tag(:td, entidad_responsable)
		end
	end


#concat(link_to 'root link', root_path)

end

app/views/expedientes/_form.html.erb
<%= form_with(model: expediente, local: true) do |form| %>
  <% if @expediente.errors.any? %>
      <% @expediente.errors.full_messages.each do |message| %>
         <%= js add_gritter(message, title: "Expedientes", sticky: false) %>
      <% end %>
  <% end %>

  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-primary btn-md", size: 50 %>
    <%= link_to 'Expedientes', expedientes_path, class: "btn btn-info btn-md", size: 50 %>
    <%= link_to 'Regresar', expediente, class: "btn btn-success btn-md", size: 50 %>
  </div><hr>

  <div class="row">
  	<div class="col-md-1">
    	<%= form.text_field :anio, placeholder: 'Año', :autofocus => true, class: "form-control" %>
	</div>

	<div class="col-md-2">
    	<%= form.text_field :expediente, placeholder: 'Número de Expediente', class: "form-control" %>
	</div>

	<div class="col-md-4">
    	<%= form.text_field :demandante, placeholder: 'Demandante', class: "form-control" %>
      <% # aqui va a ir el boton para crear los clientes  %>
	</div>

	<div class="col-md-4">
    	<%= form.text_field :demandado, placeholder: 'Demandado', class: "form-control" %>
	</div>
  </div>
<br>
  <div class="row">
    <div class="col-md-4">
      <%= form.label 'Cliente' %>&nbsp;
      <%= form.select(:cliente, [['Demandante', 'demandante'], ['Demandado', 'demandado']], { prompt: "Seleccione Abogado"} , {class: 'form-control'} ) %>
    </div>

	  <div class="col-md-4">
      <%= form.label 'Abogado' %>&nbsp;
       <%= form.collection_select(:socio,  Abogado.order(:nombre), :nombre, :nombre, { prompt: "Seleccione Abogado"} , {class: 'form-control'}) %> 
	  </div>
     
    <div class="col-md-3"> Instancia:&nbsp;
       <%= form.collection_select(:entidad_responsable_id,  EntidadResponsable.order(:nombre), :id, :nombre, { prompt: "Seleccione entidad responsable"} , {class: 'form-control'}) %> 
    </div>
    
       
      <%= form.hidden_field :estatus_procesal_id, :value => 1 %>
	   
  </div><br>
  
  <div class="row">
  	<div class="col-md-1">Referencias</div>
  	<div class="col-md-2">
    	<%= form.text_field :referencia1, placeholder: 'Referencia 1', class: "form-control" %>
    </div>
    <div class="col-md-2">
    	<%= form.text_field :referencia2, placeholder: 'Referencia 2', class: "form-control" %>
    </div>
    <div class="col-md-2">
    	<%= form.text_field :referencia3, placeholder: 'Referencia 3', class: "form-control" %>
  </div>
</div>

  <div class="row">
	<hr> 
	<div class="col-md-4">Ubicación Física:&nbsp;
      <%= form.collection_select(:location,  Location.order(:alias), :alias, :alias, { prompt: "Seleccione una ubicación"} , {class: 'form-control'}) %> 
	</div>

	<div class="col-md-2">
    <%= form.text_field :archivo, placeholder: 'Nombre de Archivo', class: "form-control" %>
  </div>
   
  <div class="col-md-2">
    <%= form.text_field :recomendado, placeholder: '¿Quién recomienda?', class: "form-control" %>
  </div>
  <div class="col-md-2">
    <%= form.text_field :en_sociedad, placeholder: 'En sociedad con...', class: "form-control" %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-6">
    <%= form.text_area :comentarios, placeholder: 'Comentarios', cols:150, rows: 2, class: "form-control" %>
  </div>


  <!--  Aqui empieza la gestion de documentos Para expedientes -->
   <div class="col-md-5">
   <h3>Documentos Anexos</h3>
      <% if @expediente.documentos.attached? %>
        <% @expediente.documentos.each do |upload| %>
            <div class="col-md-9">
              <% nombre_archivo = upload.filename.to_s  %>
              <%= link_to nombre_archivo.truncate(25), upload, target: '_blank' %> <br/>
            </div>
            <div class="col-md-1">
                <p><%= link_to expediente_delete_upload_documentos_path(:expediente_id => @expediente.id, 
                                  :documentos_id => upload.id), method: :delete, 
                                  data: { confirm: '¿Confirma Eliminar Archivo?' } do  %>
                      <i class="btn btn-danger btn-sm glyphicon glyphicon-trash"></i>
                <% end %>    </p>            
            </div>
           
        <% end %> 
      <% else %>
        <div class="col-md-9">
          <strong>Sin documentos anexos</strong>
        </div>
      <% end %>
      <div class="col-md-12">
        <br>
          <%= form.file_field :documentos, multiple: true, class: 'form-control' %>
      </div>
  </div>
  <!-- Aqui termina la gestion de documentos para expedientes -->
   
</div>
<hr>

  <h4>AUDIENCIAS</h4>

  <div class="row">
    <%= form.fields_for :audiencia_expedientes do |audiencia| %>
      <%= render 'audiencia_expediente_fields', f: audiencia %>
    <% end %>
   
  <div>    
    <%= link_to_add_association 'Agregar Audiencia', form, :audiencia_expedientes, class:'btn btn-primary btn-md' %>
  </div>
  </div>

<hr>
<h4>RESUMEN EXPEDIENTE</h4>
  <div class="row"> 
    <%= form.fields_for :resumen_expedientes do |resumen| %>
      <%= render 'resumen_expediente_fields', f: resumen %>
    <% end %>
  
 
  <div>    
    <%= link_to_add_association 'Historia Estado Procesal', form, :resumen_expedientes, class:'btn btn-primary btn-md' %>
  </div>
  </div>

  <h4>RESUMEN INSTANCIA</h4>  
  <div class="row"> 
    <%= form.fields_for :resumen_links do |resumen_instancia| %>
      <%= render 'resumen_link_fields', f: resumen_instancia %>
    <% end %>
  
 
  <div>    
    <%= link_to_add_association 'Agregar Resumen instancia', form, :resumen_links, class:'btn btn-primary btn-md' %>
  </div>
  </div>

<% end %>

app/views/expedientes/_resumen_expediente_fields.html.erb
<div class="nested-fields">
    <p>
        <div class="row">
            <% if logged_in?( :admin) %>
                <div class="col-md-1"><%= link_to_remove_association '', f, class: "btn btn-danger glyphicon glyphicon-trash" %></div>
            <% end %>
            <div class="col-md-2">
                <%= f.date_field :fecha_notificacion, placeholder: 'Fecha notificación', date_format: 'YYYY-MM-DD hh:mm', class: "form-control" %>
            </div>
            <div class="col-md-3">
                <%= f.collection_select(:estatus_procesal_id,  EstatusProcesal.order(:estatus), :id, :estatus, { prompt: "Seleccione estatus despacho"} , {class: 'form-control'}) %> 
            </div>	 
            <div class="col-md-5">
  	            <%= f.text_area :comentarios, placeholder: 'Comentarios', cols: 10, rows: 2, class: "form-control"  %>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-6">
                <%= f.file_field :escrito %>
            </div>
        </div> 
    </p>
</div>   

app/views/expedientes/index.html.erb
<div>
    <h3>Catálogo de Expedientes</h3>

    <%= form_tag expedientes_path, method: :get do %>
    <div class="input-group">
        <%= text_field_tag 'term', params[:term], placeholder: "Ingrese criterio de búsqueda", class: "form-control" %>
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
            </button>
        </span>
    </div>
    <% end %>

    <div class="text-center">
        <%= paginate @expedientes, window: 1 %>
    </div>

    <br>

    <table class="table">
        <thead>
            <tr>
                <th>Expediente</th>
                <th>Demandante</th>
                <th>Demandado</th>
                <th>Entidad Responsable</th>
                <th>Estado Procesal</th>
                <th>Próxima Audiencia</th>
                <th>Acciones</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <% @expedientes.each do |expediente| %>
            <tr>
                <% case expediente.anio %>
                <% when 2012 %>
                <td class="content-box-blue">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2013 %>
                <td class="content-box-purple">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2014 %>
                <td class="content-box-grey">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2015 %>
                <td class="content-box-rojo">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2016 %>
                <td class="content-box-federal">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2017 %>
                <td class="content-box-orange">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2018 %>
                <td class="content-box-buro">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2019 %>
                <td class="content-box-pink">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% when 2020 %>
                <td class="content-box-brown">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% else %>
                <td class="content-box-black">
                    <h4><%= link_to expediente.expediente, expediente  %></h4>
                </td>
                <% end %>

                <td><%= expediente.demandante.upcase %></td>
                <td><%= expediente.demandado.upcase %></td>
                <% instancia = EntidadResponsable.where(id: expediente.entidad_responsable_id) %>
                <td><%= instancia.first.nombre %></td>
                
                <td><%= ultimo_estado(expediente) %></td>
    
                <% audiencias = AudienciaExpediente.where(expediente_id: expediente.id).last %>
                <% if !audiencias.nil? and audiencias.fecha > Date.today %>
                <td><%= audiencias.fecha.strftime("%d-%m-%Y %H:%M") %></td>
                <% else %>
                <td>Sin proxima audiencia </td>
                <% end %>


                <% if logged_in?( :admin) %>
                <td><%= link_to expediente, method: :delete, data:{ confirm: '¿Confirma eliminar el registro?'}, class: "btn btn-danger"  do %>
                    <i class="glyphicon glyphicon-trash"></i>
                    <% end %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>

</div>

app/views/expedientes/show.html.erb
<%= link_to "Modificar", edit_expediente_path(@expediente), class: "btn btn-success btn-md" %>
<%= link_to 'Expedientes', expedientes_path, class: "btn btn-primary btn-md" %>
  

<div class="row">
	<div class="col-md-7">
		<h3 class="btn btn-info btn-lg">Número Expediente: <%= @expediente.expediente %>&nbsp;&nbsp;Año: <%= @expediente.anio %></h3>
		<h4><%= @expediente.demandante.upcase  %> <strong>vs</strong> <%= @expediente.demandado.upcase %></h4>
		<h5><strong>INSTANCIA:</strong>&nbsp;<%= @expediente.entidad_responsable.nombre.upcase %> </h5>
		<h5 class="btn btn-danger">ESTADO PROCESAL:&nbsp;<%= ultimo_estado(@expediente) %></h5>
		<h5><%=  %></h5>
	</div>
	<div class="col-md-5">
		<h4> Resumen </h4>
		<% linea_tiempo(@expediente).each do |item| %>
		
 			<div class="row">
 				<div class="col-md-2">
 					<%= item[0].strftime("%d/%m/%Y") %>
 				</div>
 				<div class="col-sm-3 linea_tiempo"> </div>
 				<div class="col-md-7">
 					<%= item[2].capitalize + ' => ' + item[1].capitalize %>
 				</div>
 			</div>
 		<% end %>
	</div>
	<div class="col-md-7"> 
		<% if !@expediente.location.nil? %>
			<p><strong>Ubicación:</strong>&nbsp;<%= @expediente.colonia(@expediente.location).upcase + ' (' + @expediente.location + ')' %> </p>
		<% end %>
		<p><strong>Responsable:</strong>&nbsp;<%= @expediente.socio %></p>
		<% if !@expediente.recomendado.blank? %>
			<p><strong>Recomendado:</strong>&nbsp;<%= @expediente.recomendado %></p>
		<% end %>
		<% if !@expediente.en_sociedad.blank? %>
			<p><strong>Sociedad:</strong>&nbsp;<%= @expediente.en_sociedad %></p>
		<% end %> 
		<% if !@expediente.referencia1.blank? %>
			<p><strong>Referencias:</strong>&nbsp;
			<%= @expediente.referencia1.upcase %> 
		<% end %>
		<% if !@expediente.referencia2.blank? %>
			<strong>|</strong>&nbsp;<%= @expediente.referencia2.upcase %> 
		<% end %>
		<% if !@expediente.referencia3.blank? %>
			<strong>|</strong>&nbsp;<%= @expediente.referencia3.upcase %> 
		<% end %>
		<% if !@expediente.comentarios.blank?  %>
			<p><strong>COMENTARIOS:</strong>&nbsp;<%= @expediente.comentarios.to_s.upcase %></p>
		<% end %>
		</p>
		
		<% if @expediente.documentos.attached? %>
			<strong>Documentos Anexos:</strong>&nbsp;
        	<% @expediente.documentos.each do |documento| %>
              <% nombre_archivo = documento.filename.to_s  %>
              <strong>|</strong>&nbsp;<%= link_to nombre_archivo.truncate(25), documento, target: '_blank'  %>
			<% end %>
		<% end %>
	</div>
	<hr>
</div>
</br>

<p>
  <a class="btn btn-primary" data-toggle="collapse" href="#audiencias" role="button" aria-expanded="false" aria-controls="audiencias">Audiencias</a>
  <button class="btn btn-verde" type="button" data-toggle="collapse" data-target="#despacho" aria-expanded="false" aria-controls="despacho">Despacho</button>
  <button class="btn btn-gris" type="button" data-toggle="collapse" data-target="#instancia" aria-expanded="false" aria-controls="despacho"><%= @expediente.entidad_responsable.nombre.capitalize %></button>
  <button class="btn btn-success" type="button" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="audiencias despacho instancia">Mostrar Todo</button>
</p>
<div class="row">
  <div class="col">
    <div class="collapse multi-collapse" id="audiencias">
      <div class="card card-body">
      	<div class="card audiencias">
      		<table class="table">
				<thead>
   					<tr>
     					<th>Fecha inicio</th>
						<th>Fecha término</th>
     					<th>Expediente</th>
     					<th>Instancia</th>
     					<th>Asignado</th>
     					<th>Motivo de audiencia</th>
						<th>Estatus</th>
						<th>Anexos</th>
   					</tr>
  				</thead>
					
				<tbody>
					<% @expediente.audiencia_expedientes.order(:fecha).each do |audiencia| %>
						<tr>
							<td><%= audiencia.fecha.strftime("%d/%m/%Y %H:%M:%S") if !audiencia.fecha.nil? %></td>
							<td><%= audiencia.fecha_fin.strftime("%d/%m/%Y %H:%M:%S") if !audiencia.fecha_fin.nil? %></td>
							<td><%= audiencia.expediente.expediente %></td> 
							<td><%= audiencia.expediente.entidad_responsable.nombre %></td>
							<td><%= audiencia.asignado.upcase if !audiencia.asignado.nil? %></td>
							<% if audiencia.comentarios.nil? %>
								<td><%= audiencia.comentarios %></td>
							<% else %>
								<td><%= audiencia.comentarios.upcase %></td>
							<% end %>
							<td><%= audiencia.estatus_audiencia.estatus.upcase %></td>
							<% if audiencia.citatorio.attached? %>
								<td><%= link_to audiencia.citatorio.filename, audiencia.citatorio, target: '_blank', style: 'color:Black;' %> </td>
							<% end %>
							
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>         
      </div>
    </div>
  </div>

  <div class="col">
    <div class="collapse multi-collapse" id="despacho">
      <div class="card card-body">
        <div class="mi_estado_procesal">
			<table class="table">
				<thead>
   					<tr>
    			 		<th>Fecha notificación</th>
						 <th>Estado procesal</th>
						 <th>Detalle</th>
						 <th>Anexos</th>
   					</tr>
  				</thead>
		
				<tbody>
					<% @expediente.resumen_expedientes.order(:fecha_notificacion).each do |resumen| %>
						<tr>
							<td><%= resumen.fecha_notificacion.strftime("%d/%m/%Y") if !resumen.fecha_notificacion.nil? %></td>
							<td><%= resumen.estatus_procesal.estatus %></td>
							<% if resumen.comentarios.nil? %>
								<td><%= resumen.comentarios %></td>
							<% else %>
								<td><%= resumen.comentarios.upcase %></td>
							<% end %>
							
							<% if resumen.escrito.attached? %>
								<td><%= link_to resumen.escrito.filename, resumen.escrito, target: '_blank', style: 'color:Black;' %> </td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="collapse multi-collapse" id="instancia">
      <div class="card card-body">
        <div class="entidad_estado_procesal">
			<table class="table">
				<thead>
			   		<tr>
			     		<th>Fecha publicación</th>
			     		<th>Acción</th>
						 <th>Comentarios</th>
			   		</tr>
			  	</thead>
					
				<tbody>
					<% @expediente.resumen_links.order(:fecha_publicacion).each do |links| %>
						<tr>
							<td><%= links.fecha_publicacion.strftime("%d/%m/%Y") if !links.fecha_publicacion.nil? %></td>
							<% if links.comentarios.nil? %>
								<td><%= links.comentarios %></td>
							<% else %>
								<td><%= links.comentarios.upcase %></td>
							<% end %>
							<td><%= links.accion_instancium.accion %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
      </div>
    </div>
  </div>
</div>