config/routes.rb
Rails.application.routes.draw do
  get 'paginas/inicio', as: 'inicio'
  get 'paginas/consulta', as: 'consulta'
  get 'paginas/estadistica', as: 'estadistica'


  devise_for :users, path: '', path_names: { sign_in: 'ingresar', sign_out: 'Salir', sign_up: 'registrar'}

  resources :expedientes do
    delete :delete_upload_documentos
  end
  
  resources :estatus_procesals
  resources :estatus_audiencias
  resources :entidad_responsables
  resources :audiencias
  resources :audit_logs
  resources :holidays
  resources :abogados
  resources :links
  resources :accion_instancia
  resources :cuestionarios
  resources :despachos
  
  
  root to: "paginas#inicio" 


end

app/models/despacho.rb
class Despacho < ApplicationRecord
	has_many :locations, inverse_of: :despacho, dependent: :destroy 
	 

	accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

	def abogado(id)
    	abogado = Abogado.where(id: id).first.nombre
    end 

end

app/controllers/despachos_controller.rb
class DespachosController < ApplicationController
	before_action :set_despacho, only: [:edit, :update, :destroy]
  access admin: :all

  def index
    @despachos = Despacho.all
  end

  def new
    @despacho = Despacho.new
  end

  def edit

  end

  def create
      @despacho = Despacho.new(despacho_params)
      respond_to do |format|
          if @despacho.save
            format.html { redirect_to despachos_path, notice: 'Regsitro creado correctamente.' }
          else
            format.html { render :new }
          end
      end
    end

    def update
      respond_to do |format|
        if @despacho.update(despacho_params)
          format.html { redirect_to  despachos_path, notice: 'Regsitro actualizado correctamente.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      if @despacho.destroyed?
      respond_to do |format|
        format.html { redirect_to despachos_path, notice: 'Regsitro eliminado correctamente.' }
      end
    else
      respond_to do |format|
        format.html { redirect_to despachos_path, alert: 'Favor de intentar mas tarde.' }
      end
    end
    end

    private
    
    def set_despacho
      @despacho = Despacho.find(params[:id])
    end

    def despacho_params
      params.require(:despacho).permit(:id, :colonia, :calle, :numero, :abogado_id,
                         locations_attributes: [:id, :archivero, :cajon, :alias, :despacho_id, :_destroy])
    end

end

app/views/despachos/_form.html.erb
<%= form_for(@despacho, html: { multipart: true }, remote: local_assigns[:hide_buttons]) do |form| %>
<% if @despacho.errors.any? %>
      <% @despacho.errors.full_messages.each do |message| %>
         <%= js add_gritter(message, title: "Aviso", sticky: false) %>
      <% end %>
  <% end %>

<div class="field">
  <%= form.label :colonia %>
  <%= form.text_field :colonia, class: "form-control", placeholder: "Colonia", required: true %>
  <%= form.label :calle %>
  <%= form.text_field :calle, class: "form-control", placeholder: "Calle", required: true %>
  <%= form.label :numero %>
  <%= form.text_field :numero, class: "form-control", placeholder: "Número", required: true %>
  <p><%= form.label 'Abogado Responsable' %>&nbsp;
  <%= form.collection_select :abogado_id, Abogado.order(:nombre),:id,:nombre, include_blank: true,  class: "form-control" %> 
</p>
  
 

</div>
<h4>Ubicaciones</h4>

  <div class="row">
    <%= form.fields_for :locations do |location| %>
      <%= render 'location_fields', f: location %>
    <% end %>
   
  <div>    
    <%= link_to_add_association 'Agregar ubicación', form, :locations, class:'btn btn-primary btn-md' %>
  </div>
  </div>

  <br>
  <% unless local_assigns[:hide_buttons] %>
  <div class="actions">&nbsp;
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
      <span><i class="glyphicon glyphicon-pencil"></i> Guardar</span>
    <% end %>  
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
      <span><i class="glyphicon glyphicon-list"></i></span>
      Catálogo
    </button>
  </div>
  <% end %>

<% end %>

 

app/views/despachos/_location_fields.html.erb
<div class="nested-fields">
    <p>
        <div class="row">
            <% if logged_in?( :admin) %>
                <div class="col-md-1"><%= link_to_remove_association '', f, class: "btn btn-danger glyphicon glyphicon-trash" %></div>
            <% end %>
            <div class="col-md-3">
                <%= f.text_field :archivero, placeholder: 'Núm. Archivero', class: "form-control", required: true %>
            </div>
            <div class="col-md-3">
                <%= f.text_field :cajon, placeholder: 'Núm. Cajón', class: "form-control", required: true %> 
            </div>
            <div class="col-md-3">	 
                <%= f.text_field :alias, placeholder: 'Alias', class: "form-control", required: true, prompt: 'Choose an existing owner' %> 
            </div>
        </div>
         
    </p>
</div>  


 
 

app/views/despachos/edit.html.erb
<%= form_with(model: @despacho, local: true) do |form| %>	
  <%= form.submit "Guardar", class: 'btn btn-success' %>
<% end %>
<%= link_to "Regresar a Catálogo", despachos_path, class: "btn btn-primary" %>

app/views/despachos/edit.js.erb
$('#form-modal-title').html("<i class='glyphicon glyphicon-plus'></i>&nbsp;&nbsp;Actualizar Ubicaciones");
$('#form-modal-body').html('<%= j render("form" ) %>');
$('#form-modal').modal('show');
$('#form-modal-save-btn').click(function() {
	$('#new_tipo_montaje').submit();
});

app/views/despachos/index.html.erb
<h4>Catálogo Ubicaciones</h4>
<div>
	<%= form_tag despachos_path, method: :get do %>
  		<div class="input-group">
      		<%= text_field_tag 'term', params[:term], placeholder: "Ingrese criterio de búsqueda", class: "form-control" %>
      		<span class="input-group-btn">
            	<button class="btn btn-default" type="submit">
                	<i class="glyphicon glyphicon-search"></i>
            	</button>
        	</span>
    	</div><br>
    	<%= link_to new_despacho_path, class: "btn btn-primary", remote: true  do %>
			<i class="glyphicon glyphicon-plus"></i>
				Agregar Ubicaciones
    	<% end %>
  <% end %>
</div>

 
<div class="modal" tabindex="-1" role="dialog" id="form-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="form-modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="form-modal-body">        
      </div>
    </div>
  </div>
</div>

<table class="table">
	<thead>
		<tr>
			<th>Despacho</th>	
			<th>Calle y Número</th>
			<th>Responsable</th>
			<th>Total Ubicaciones</th>
		</tr>
	</thead>
	<tbody>
		<% @despachos.each do |despacho| %>
			<tr>
				<td><%= despacho.colonia %></td>
				<td><%= despacho.calle + ' ' + despacho.numero %></td>
				<td><%= despacho.abogado(despacho.abogado_id) %> </td>
				<td><%= despacho.locations.count %></td>
				<td><%= link_to  edit_despacho_path(despacho), class: "btn btn-info", remote: true  do %>
						<i class="glyphicon glyphicon-pencil"></i>
					<% end %>

					<%= link_to despacho, method: :delete, data:{ confirm: '¿Confirma eliminar el registro?'}, class: "btn btn-danger"  do %>
						<i class="glyphicon glyphicon-minus"></i>
					<% end %>
				</td>
			</tr>
		<% end %>

	</tbody>
</table>

app/views/despachos/new.html.erb
<%= form_with(model: @despacho, local: true) do |form| %>
  
  <%= form.submit "Guardar", class: 'btn btn-success' %>
<% end %>
<%= link_to "Regresar a Catálogo", despachos_path, class: "btn btn-primary" %>

app/views/despachos/new.js.erb
$('#form-modal-title').html("<i class='glyphicon glyphicon-plus'></i>&nbsp;&nbsp;Crear Entidad Responsable");
$('#form-modal-body').html('<%= j render("form" ) %>');
$('#form-modal').modal('show');
$('#form-modal-save-btn').click(function() {
	$('#new_despacho').submit();
});